### ISSUE TITLE
Clean commits? I beg to differ.

### ISSUE THREAD

**Issue by b-boehne** [avenga/coding-guidelines#10]
This issue relates to one of the [Git Guidelines](https://github.com/avenga/coding-guidelines/blob/master/general/avenga-git-guidelines.md#commits) which I would like to open for discussion. Namely this one:

>### Commits
>* **Clean commits:** Commits must only contain changes related to the task/feature you are working on.

&nbsp;
I'm a firm believer to further slow down code rot and to combat "broken window theory" type coding ([as visualized here](https://www.monkeyuser.com/2019/code-entropy/)), any programmer should develop an "Always leave the campground cleaner than you found it." mindset.
[Uncle Bob also wrote this in his "Clean Code"](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)

To make my point, I feel this "clean commits" rule kind of prohibits cleaning up the campground even if my task is to add some new feature. Adding small code cleanups or refactorings to my PRs should be encouraged, not complicated for the dev. If I have to create a new branch and open a separate PR for miniscule changes it would discourage me from doing it in the first place.  

If, by any chance, this rule only specifies that one should create separate commits for changes not related to the current task (which I would support 100%), I would at least like to change the wording of it.

**Comment by GrzegorzMachnik** [comment]
But it is much easier to review code if you at least make two commits, one with core changes (functional or not) and the second one with code cleanup if is not related to the core problem. But generally, IMHO this point can be improved as you suggest.

**Comment by b-boehne** [comment]
Yes I agree, but I read the rule as if you should not add them at all.  
If it is not meant as such than I would vote to change the wording of the rule like so:

* **Clean commits:** Changes not related to the task/feature you are working on should be included in separate commits.

**Comment by frederik-b** [comment]
@b-boehne I agree with your new wording, can you create a PR?
